name: base_image

on:
  push:
    branches:
      - develop
    paths:
      - base/redhat-8/**

jobs:
  build_base_image:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set environment variables
        run: |
          echo $(grep "SPLUNK_VERSION " Makefile | cut -d " " -f3) > tag_splunk_version
          echo $(grep "SCLOUD_URL " Makefile | cut -d " " -f3) > tag_scloud_url

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build base image
        run: |
          docker build \
          --build-arg SCLOUD_URL=$(cat tag_scloud_url) \
          --label version=$(cat tag_splunk_version) \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/redhat-8:latest \
          ./base/redhat-8

      - name: Push base image to Docker Hub
        run: docker push --all-tags ${{ secrets.DOCKER_HUB_USERNAME }}/redhat-8

      - name: Trigger splunk_image workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/workflows/splunk_image.yml/dispatches \
          -d '{"ref":"develop"}'
