# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: base_image

on:
  push:
  # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - develop
    paths:
      - base/redhat-8/*

jobs:
  makefile:
    name: base_image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: set some envs
        run: |
          echo $(grep "SPLUNK_VERSION " Makefile | cut -d " " -f3) > tag_splunk_version
          echo $(grep "SCLOUD_URL " Makefile | cut -d " " -f3) > tag_scloud_url

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v3
        with: 
          push : true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/redhat-8:latest
          label: version=${{ cat tag_splunk_version }}
          build-args: SCLOUD_URL=${{cat tag_scloud_url }}
          context: ./base/redhat-8